### ISSUE TITLE
Confusion regarding FID score for True data

### ISSUE THREAD

**Issue by PrateekMunjal** [tolstikhin/wae#7]
I am currently using [TTUR implementation](https://github.com/bioinf-jku/TTUR) to compute FID scores where we need to pass 2 things i.e <path_to_generated_samples> and <path_to_original_images> or <path_to_pre-computed_statistics_file>.

Now I am confused for the value of FID corresponding to True data(reference to celebA) i.e how do we evaluate it?
According to my understanding, the FID for true data is computed in following steps : 
1. Sample two sets of 10k size from cropped celebA dataset(where images are of 178x218). -- say S1 and S2.
2. Preprocess & Resize the images in S1 & S2 such that image size is 64x64.
3. Now run "fid.py <path_to_S1> <path_to_S2>" -- this gives me an FID of score around 2 i.e with different samples value fluctuates in 1.6 to 2.3.

So is this same process you followed for computing FID ?

So if above is correct then further speculating I can compute FID by generating samples from my generator which construct images of 64x64 -- say G1 directory. Then to compare FID for this model we just need to run "fid.py <path_to_G1> <path_to_S1/S2>" ?

PS : I did not find much resources explaining the end to end procedure for computing FID, so asked here.  By the way I really enjoyed your paper reading. It's very well written, learnt a lots of maths !!

 Regards,
Prateek

**Comment by tolstikhin** [comment]
Hey,

you got it all right! That is exactly how FID scores were evaluated. 

Ilya

**Comment by PrateekMunjal** [comment]
Thanks for clarification!
